### ISSUE TITLE
Align Carrier Billing Event with CloudEvents structure

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/CarrierBillingCheckOut#112]
**Problem description**
At least :) we achieve the conclusion on the notification pattern in Commonalities.
Now time to align our API

**Expected behavior**
API aligned with Commonalities

**Alternative solution**
Not sure.

**Additional context**

**Comment by PedroDiez** [comment]
Agree @bigludo7

**Comment by PedroDiez** [comment]
25/OCT: To be included in next PR generation

**Comment by PedroDiez** [comment]
Closed as per [PR#119](https://github.com/camaraproject/CarrierBillingCheckOut/pull/119) MERGED
