### ISSUE TITLE
Purchase Conversion Event

### ISSUE THREAD

**Issue by nickvenezia** [camaraproject/CarrierBillingCheckOut#139]
This API would be a good source of purchase activity data, especially as an advertising objective designated "purchase conversion event" for a campaign. As the API is defined, advertisers would want a field to track the conversion event callback to allow ad campaigns to collect information about conversion events / app purchases.

Background context
https://www.wordstream.com/blog/ws/2021/10/06/facebook-conversions-api

Here is how Meta handles conversion tracking 
https://developers.facebook.com/docs/marketing-api/conversions-api/using-the-api#verify

**Comment by bigludo7** [comment]
Hi @nickvenezia 
Could you be a more specific about your request?
As of now we have in the API model attribute like  `clientCorrelator` that could be use to link the payment request to previous event and probably manage conversion management.

**Comment by nickvenezia** [comment]
What type of insights can I help with?

**Comment by bigludo7** [comment]
@nickvenezia 
This API is about payment and not to purchase.
But you can get from this API the `phoneNumber` that must be charged (not the buyer but the payer - I guess in some UC could be distinct), the charging amount and timestamp for `paymentCreationDate `and `paymentDate`.

**Comment by PedroDiez** [comment]
Hi @nickvenezia, think this issue can be closed with the clarifications provided by Ludovic, doesn't?

**Comment by nickvenezia** [comment]
@PedroDiez @bigludo7 correct. This issue can be closed

**Comment by PedroDiez** [comment]
Thanks for quick answer Nick!
