### ISSUE TITLE
Error Model aligment with Commonalities Meta-Release Fall24

### ISSUE THREAD

**Issue by PedroDiez** [camaraproject/CarrierBillingCheckOut#154]
**Problem description**
In the Context of [Commonalities/Issue 180](https://github.com/camaraproject/Commonalities/issues/180) and [Commonalities/Issue 127](https://github.com/camaraproject/Commonalities/issues/127). An error model alingment is required.

@bigludo7 also commented in 17th April meeting that could make sense to have some errors being addressed with 422 exception instead of 403 one.

Based on that aligment, it would be required to make proper adaptations in both carrier billing payment and carrier billing refund functionality.

**Possible evolution**
Pending to be proposed

**Alternative solution**
N/A

**Additional context**
N/A

**Comment by PedroDiez** [comment]
Please find attached error model aligment porposal to discuss today (based on Commonalities Aligment PR#213)

[CB_Error_Model_Alignment_Proposal.xlsx](https://github.com/user-attachments/files/15804057/CB_Error_Model_Alignment_Proposal.xlsx)

cc @bigludo7, @rartych, @eragaji

**Comment by PedroDiez** [comment]
Hi,

@bigludo7, @rartych please can you provide feedback? Based on that we can try to reach a conclusion about updates in error excepctions

**Comment by bigludo7** [comment]
Hello @PedroDiez 
Sorry to be late on this.
Took a look.

Only one comment :
I'm bit skeptical of the propose use of 429 for CARRIER_BILLING.USER_AMOUNT_THRESHOLD_OVERPASSED. For me

- 429 is used if we got too many 'technical' request from a consumer. I'm not thinking of a business error.
- Here we have a business error (for my understanding) - as a carrier billing operator we do not allow consumer to spend more than x euros per month on Carrier billing payment. In this case I will probably more expect a 422 (and the code CARRIER_BILLING.USER_AMOUNT_THRESHOLD_OVERPASSED is perfect).

**Comment by PedroDiez** [comment]
> Hello @PedroDiez Sorry to be late on this. Took a look.
> 
> Only one comment : I'm bit skeptical of the propose use of 429 for CARRIER_BILLING.USER_AMOUNT_THRESHOLD_OVERPASSED. For me
> 
> * 429 is used if we got too many 'technical' request from a consumer. I'm not thinking of a business error.
> * Here we have a business error (for my understanding) - as a carrier billing operator we do not allow consumer to spend more than x euros per month on Carrier billing payment. In this case I will probably more expect a 422 (and the code CARRIER_BILLING.USER_AMOUNT_THRESHOLD_OVERPASSED is perfect).

Understood @bigludo7, makes sense to use 422, also being compliant with the guidelines. For the rest of the proposal, I guess you seems right, doesn't?

**Comment by bigludo7** [comment]
@PedroDiez 

> For the rest of the proposal, I guess you seems right, doesn't?

Yes the rest of the proposal is fine for me :)

**Comment by PedroDiez** [comment]
Will wait EOD this Thursday to check other comments and moving forward with the updates

**Comment by PedroDiez** [comment]
Already covered in #152
