### ISSUE TITLE
Update API Readiness Checklist format and information for Meta-Release Fall24

### ISSUE THREAD

**Issue by PedroDiez** [camaraproject/CarrierBillingCheckOut#163]
**Problem description**
API Readiness Checklist format has been update by Release Management WG: https://github.com/camaraproject/ReleaseManagement/blob/main/documentation/API-Readiness-Checklist.md

**Expected action**
It is needed to adapt this checklist for the APIs involved in MetaRelease Fall24:
- Carrier Billing Payment
- Carrier Billing Refund

Document as a reference: 
https://github.com/camaraproject/CarrierBillingCheckOut/blob/main/documentation/API_documentation/Carrier%20Billing-API-Readiness-Checklist.md

**Additional context**
It is proposed to keep the same file and document within it two tables, one per API.

**Comment by hdamker** [comment]
> It is proposed to keep the same file and document within it two tables, one per API.

Actually the process asks for one file per API, as the files should be prefixed with the API Names (`carrier-billing` and `carrier-billing-refund`).

**Comment by PedroDiez** [comment]
> > It is proposed to keep the same file and document within it two tables, one per API.
> 
> Actually the process asks for one file per API, as the files should be prefixed with the API Names (`carrier-billing` and `carrier-billing-refund`).

Thanks for the info @hdamker. We will then generate two files
