### ISSUE TITLE
Convention for file names of API definition

### ISSUE THREAD

**Issue by rartych** [camaraproject/CarrierBillingCheckOut#175]
**Problem description**
There is currently no guidelines for file names of API definition files in CAMARA.
The initially agreed proposal is to use the convention api-name.yaml as a guideline for the API definition file names.

**Expected behavior**
Change the file names to kebab-case before or as a part of release PR for M4.

**Alternative solution**
Wait for the final guidelines.

**Additional context**
See the discussion in [Commonalities](https://github.com/camaraproject/Commonalities/issues/284)

**Comment by PedroDiez** [comment]
Doing it as part of release 1.2 PR
