### ISSUE TITLE
Carrier Billing Partial Refund: No Amount Field Available for /payments/{paymentId}/refunds

### ISSUE THREAD

**Issue by ajmhussain** [camaraproject/CarrierBillingCheckOut#181]
**Problem description**
Carrier Billing Refund POST API (/payments/{paymentId}/refunds) has an option to opt for total refund or partial refund. type element in the request has following enum:
[ total, partial ]

However, for partial refund, there is no field to specify the amount. 

**Possible evolution**

amount field should be there to specify the required refund amount in case of partial refund. 
**Alternative solution**

**Additional context**

**Comment by PedroDiez** [comment]
Hi @ajmhussain,

It is already considered [Carrier Billing Refund v0.1](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/camaraproject/CarrierBillingCheckOut/r1.2/code/API_definitions/carrier-billing-refund.yaml&nocors)

As it may be observed:
![image](https://github.com/user-attachments/assets/2cefe1da-b012-47a5-a9e7-dd8f5cc72e17)

"amount" to be refunded can be indicated within amountTransaction -> refundAmount -> chargingInformation

**Comment by PedroDiez** [comment]
@ajmhussain please comment if this resolve your comment so as we can close the issue

**Comment by ajmhussain** [comment]
Hi @PedroDiez The public release that is available on the below link doesn't match to what you shared:
https://github.com/camaraproject/CarrierBillingCheckOut?tab=readme-ov-file
Screenshot below:
![image](https://github.com/user-attachments/assets/86377f9f-c51a-4142-8156-df980f9ee64a)

**Comment by PedroDiez** [comment]
Hi @ajmhussain, 

It seems a matter of renderization by swagger editor.
The definition includes it and within redoc is well renderized

**Comment by ajmhussain** [comment]
Hi @PedroDiez 

There seems some issue with the specs due to which it is not getting rendered correctly. All other CAMARA APIs we always check through Swagger Editor and proceed accordingly.

**Comment by PedroDiez** [comment]
Hi,

@ajmhussain we set this issue to closed as it is swagger editor topic.
