### ISSUE TITLE
Open contributions to this WG

### ISSUE THREAD

**Issue by PedroDiez** [camaraproject/CarrierBillingCheckOut#21]
Hi all,

Currently, there are two different paradigms to deal with the functionality under this WG.

* One baseline contribution from Telefonica. https://github.com/camaraproject/CarrierBillingCheckOut/issues/3 (PR: https://github.com/camaraproject/CarrierBillingCheckOut/pull/4). Orange has indicated they would not accept such proposal.

* Other baseline contribution from Orange. https://github.com/camaraproject/CarrierBillingCheckOut/pull/16. Telefonica has also indicated they would not accept such porposal.

Rationale of discussion is within the comments of the discussions in both threads.

Would also like to see opinion of other participants. 
@alabajnaid from STC side what is your view?

**Comment by PedroDiez** [comment]
Hi,

Ludovic @bigludo7, we need to align the name of both "yaml" proposals.

![image](https://user-images.githubusercontent.com/6905728/206133111-49e05f6a-3a12-4158-947e-95a4af0403d8.png)

Propose the following to name the yamls:
- Orange Proposal: carrier_billing_payment.yaml
- Telefónica Proposal: carrier_billing_checkout.yaml

Set both to v0.5 (future aligment with CAMARA guidelines will be needed)

Within yaml, api names:
- Orange: the name you consider suitable (you can keep "payment"). Anycase up to your consideration
- Telefonica: it will be named "carrier-billing-checkout"

**Comment by bigludo7** [comment]
Hello @PedroDiez 
Yes, carrier_billing_payment.yaml + v0.5 works for me.

I prepare a pull request to add the file.
Thanks

**Comment by PedroDiez** [comment]
Next Step @bigludo7. We have to prepare documentation for both proposals. That is needed to match milestones

I will comment in the meeting. 
https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/API-Readiness-Checklist.md (point 3)

Just an example reference:
https://github.com/camaraproject/QualityOnDemand/blob/main/documentation/API_documentation/QoD_API.md

**Comment by PedroDiez** [comment]
Have already merged pending PRs.

**Comment by PedroDiez** [comment]
Closed this issue. Both contributions documentation ready
