### ISSUE TITLE
Align Error Structure with design guideline

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/CarrierBillingCheckOut#44]
Already discussed before the break but to be sure to not forget it: We should align error structure in both flavor with adding a _status_ attribute. Source: https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/API-design-guidelines.md#6-error-responses.

**Comment by PedroDiez** [comment]
Agreed during 18th Januaty meeting to align proposals on this matter

**Comment by PedroDiez** [comment]
Think we can close this issue

**Comment by bigludo7** [comment]
Yes it has been implemented in our swaggers.
