### ISSUE TITLE
Update readme.md file to indicate that 2 flavors are defined

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/CarrierBillingCheckOut#46]
Hello,

As we have 2 distinct flavors of carrier billing api: one with purchase/payment and the other with payment only we should indicate this i the readme file to introduce this API specificity to the developer browsing our API.

If make sense I can provide suggestion.

**Comment by PedroDiez** [comment]
Ok, Ludovic, please you can provide proposal

**Comment by PedroDiez** [comment]
Thanks @bigludo7!! for this thread, the suggestion and the proposal.

Closing this issue as PR is already merged
