### ISSUE TITLE
Maintainers

### ISSUE THREAD

**Issue by PedroDiez** [camaraproject/CarrierBillingCheckOut#5]
Is anyone willing to be a maintainer? Please comment in this thread
Current Maintainers: https://github.com/camaraproject/CarrierBillingCheckOut/blob/main/MAINTAINERS.MD

**Comment by PedroDiez** [comment]
Close this issue

**Comment by ShutingQing** [comment]
Hi @PedroDiez @bigludo7 @ToshiWakayama-KDDI , hope you're doing well. Currently is there still any requirements for volunteers to maintain this project? I'm interested in carrier billing check out, and want to make efforts here.

**Comment by bigludo7** [comment]
Hello @ShutingQing 
Thanks for your proposal.
We are maintaining the project, in particular with @PedroDiez, to provide code and host meetings. 
We can discuss this during next meetings perhaps?

**Comment by ShutingQing** [comment]
Yes, sure, thank you for replying. :)
