### ISSUE TITLE
OPEN QUESTIONS - Carrier Billing Payment Proposal

### ISSUE THREAD

**Issue by PedroDiez** [camaraproject/CarrierBillingCheckOut#55]
**Issue to track questions & comments received regarding Carrier Billing Payment Proposal**

- [x] Q1: Payment - Management of taxes: STC indicates it is needed in some way to indicate if an amount includes taxes or not. Orange comments "taxAmount" is an optional parameter in case merchant wants to indicate it. Ericsson porposes to have a boolean to indicate if "amount" has taxes. 

NOTE: Opened until other mates can have access to WG and open issues Ludovic

**Comment by bigludo7** [comment]
Thanks
Agreed. I will make a proposal for next version.

**Comment by bigludo7** [comment]
Swagger proposal here: https://github.com/camaraproject/CarrierBillingCheckOut/pull/60

Please provide feedback and once agree I will update the documentation. thanks

**Comment by PedroDiez** [comment]
Set to closed as covered in PR https://github.com/camaraproject/CarrierBillingCheckOut/pull/60
