### ISSUE TITLE
Design Guidelines: HTTP Status Code type should be Integer, not String

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/CarrierBillingCheckOut#58]
Hi
We need to change again :)

See https://github.com/camaraproject/WorkingGroups/issues/143 

No hurry there for next API update we should align.

**Comment by PedroDiez** [comment]
hahaha, yes Ludovic. 

Let's wait until the conclusion of that track, because as an integer, "pattern" concept does not apply but the use of:
_minimum: 
maximum:_
probably would be the suitable one. 
Think this is gonna be moved in Commonalities

**Comment by PedroDiez** [comment]
Let's keep this Issue Open.
Think can take still some time to have an alignment. Just to have track of it when considering this in a higher version

**Comment by PedroDiez** [comment]
Open thread in Commonalities: https://github.com/camaraproject/WorkingGroups/issues/151

**Comment by PedroDiez** [comment]
Currently being addressed in https://github.com/camaraproject/WorkingGroups/pull/162

Model is the one fllowed within WG, just will take out pattern from "status" as pattern applies for string fields

**Comment by PedroDiez** [comment]
Set to closed as covered in PRs: https://github.com/camaraproject/CarrierBillingCheckOut/pull/60 and https://github.com/camaraproject/CarrierBillingCheckOut/pull/64
