### ISSUE TITLE
snake_case guideline alignement

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/CarrierBillingCheckOut#61]
NOTE: As per guidelines, https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/API-design-guidelines.md

input/output params will be snake_case, so for a v1 we need to check in both proposals we are compliance with it.

https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/API-design-guidelines.md#42-inputoutput-resource-definition

_These considerations are below:
* API input and output business data will follow the snake_case notation._

_Originally posted by @PedroDiez in https://github.com/camaraproject/CarrierBillingCheckOut/issues/56#issuecomment-1431490244_

**Comment by PedroDiez** [comment]
Thanks for generating separate track @bigludo7.

Currently, the guidelines indicates the use of snake_case for input/output params. 
Just to bear in mind looking forward a v1.0.0, we need to review it in proposals.

Have already check sim_swap an it is already done -> https://github.com/camaraproject/SimSwap/blob/main/code/API_definitions/CAMARA/checkSimSwap-v0.3.0.camara.swagger.yaml

And in QoD, they are in the process of adapting it.

**Comment by PedroDiez** [comment]
This topic is to be addressed in commonalities. Orange will open thread for second-think about it

**Comment by PedroDiez** [comment]
I am going to close this issue @bigludo7 
As guidelines in CAMARA are updated and the changes are already being covered in PRs within this WG.
PR 60 - https://github.com/camaraproject/CarrierBillingCheckOut/pull/60 (Merged)
PR 64 - https://github.com/camaraproject/CarrierBillingCheckOut/pull/64 (Ongoing)
