### ISSUE TITLE
Update Github PR Template

### ISSUE THREAD

**Issue by ShutingQing** [camaraproject/CarrierBillingCheckOut#73]
Update the github pr template described in the working group. https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Issue%20and%20PR%20template%20Howto.md

**Comment by ShutingQing** [comment]
Linked to [https://github.com/camaraproject/CarrierBillingCheckOut/pull/72](url)

**Comment by PedroDiez** [comment]
Merged https://github.com/camaraproject/CarrierBillingCheckOut/pull/73

Thanks for the contribution @ShutingQing
