### ISSUE TITLE
Business Scenario for Carrier Billing Check Out

### ISSUE THREAD

**Issue by ShutingQing** [camaraproject/CarrierBillingCheckOut#76]
Hi all,

Many people asked me about the business scenario of carrier billing checkout. I think it's a common question, and we'd better **have more material illustrate why and when it's good to use operator's billing system.**

From my point, i feel like the most key value of CBCS for end users is, using this API, can to some extent, erase user's payment process. Like supposedly, user download an app, or using TV app, whatever, if they just want to make a one-time order, they do not want to bind their credit card to make the payment. **Or, another scenario, when they are filling out their credit card info, which includes the address, the card number. In this process, they change their mind and decide not to make the order.** 

Starting from this point, I made this material. Want to give people, who have interest in our project, to see our value at the first glance. 

Linked to [https://github.com/camaraproject/CarrierBillingCheckOut/pull/75](url)

**Comment by PedroDiez** [comment]
Commented on PR#75
