### ISSUE TITLE
Decision in CAMARA API for Carrier Billing

### ISSUE THREAD

**Issue by PedroDiez** [camaraproject/CarrierBillingCheckOut#79]
Hello all,

As known by participants, in the lifetime of Carrier Billing WorkingGroup there have been two proposals:

Proposal A): Carrier Billing (Checkout) - https://github.com/camaraproject/CarrierBillingCheckOut/blob/main/code/API_definitions/carrier_billing_checkout.yaml

Proposal B): Carrrier Billing (OMA-based, named Payment) - https://github.com/camaraproject/CarrierBillingCheckOut/blob/main/code/API_definitions/carrier_billing_payment.yaml

There was consensus at the end of last year two move forward with two flavours. However, several times during this year discussion has been reopened in order to have a common single one.

Informative Document jointly elaborate by Orange and Telefonica: https://github.com/camaraproject/CarrierBillingCheckOut/pull/78
cc @bigludo7 

Therefore I am proposing the following:
cc @MarkusKuemmerle 

1.- Check with Markus If a votation can be performed within WG. Contacting Offline. https://github.com/camaraproject/Governance/blob/main/ProjectCharter.md#governance

2.- In that case in which conditions. My proposal within the WG so far would be:
     - One week to vote (clear point)
     - One vote per participant/company (clear point, that would like to vote)
     - At least 5 five votes
     - Election by simple mayority (here also to open other points of view)

**Comment by bigludo7** [comment]
@PedroDiez @MarkusKuemmerle one additional though... as this vote could have direct impact on using (or not) existing standard in the industry, are we comfortable to have this vote only at project level ?

I should confess that I will more open to wait new governance and introduction of the Technical Steering Committee to trigger a discussion there and then process accordingly to TSC guidance.

**Comment by MarkusKuemmerle** [comment]
@bigludo7 : That could be a good option. So if the group feels that the decision has to be "escalated" to the TSC due to importance then this will be the right approach. And the more as this is a precedent for other API families...

**Comment by bigludo7** [comment]
Thanks @MarkusKuemmerle.
Yes from Orange perspective we prefer to have a discussion at TSC level on this topic.

**Comment by ShutingQing** [comment]
Should we just choose one of the api, or we can discuss to how can we combine the 2?

**Comment by PedroDiez** [comment]
From our side, decision could be done within WG if there is a consensus. 
@bigludo7 has indicated from Orange it is preferred to deal with this topic at TSC level.

So, as directly involved participant think there is no consensus at WG level. 

@MarkusKuemmerle, which are the steps to elevate this topic at TSC level?

**Comment by PedroDiez** [comment]
@bigludo7 @MarkusKuemmerle given the fact that TSC is not in "force" yet, and probably not in the short-term. We believe that address this topic in the next SC is a reasonable way-forward. 

While not having a decision on that and discussing where to deal with it, we are adding more delay in the Time-To-Market for having a clear guidance for any Telco willing to implement a "CAMARA" flavour of the Carrier Billing functionality supporting and enforcing the GSMA Opengateway initiative message of providing a standardized way to perform this functionality.

Really think we also should consider this

**Comment by bigludo7** [comment]
Thanks a lot @PedroDiez and it was a pleasure to collaborate on his work !
Again I will like, from Orange, to thanks Telefonica and @PedroDiez for your willingness to find an agreement on this topic.  There is no more a Telefonica or an Orange proposal but a common proposal and this is already an achievement. 
Let's work with the team to make it a CAMARA 'official' asset.
