### ISSUE TITLE
Summer Meetings Planning

### ISSUE THREAD

**Issue by PedroDiez** [camaraproject/CarrierBillingCheckOut#90]
Dear WG Participants, 

In order to manage summer meetings. I would like to propose some dates for next meetings, aiming at having at least one meeting per month.

Have synched with Ludovic and He is off the first middle of August and I will have limited availability. So for August is proposed 23th

Proposed Dates
- Wednesday, 19th July, 16:00 - 17:00 CEST
- Wednesday, 23th August, 16:00 - 17:00 CEST
- Wednesday, 06th September, 16:00 - 17:00 CEST

Let me know if that fits 
@bigludo7, @rartych , @alabajnaid, @eragaji, @ShutingQing, @FahadTanwir-STC

**Comment by ShutingQing** [comment]
Actually i'll be available. If you don't mind, let me help on this in case there are new friends coming. I'll collect new comer's proposal if someone have, and bring back to you and ludovic, and then we discuss.

**Comment by PedroDiez** [comment]
In the next meeting, you can explain with more detail your view on that.

Regarding meetings is hardly to have with more frequency that bi-weekly. Some people attend other tracks and it is also needed to review issues, comments,...

Please connect to the next meeting so we can understand better about your comment

**Comment by ShutingQing** [comment]
Yeah understood. I know that you and ludovic are maintaining not only carrier billing. 

What I'll suggest is:
1. Let's see is there any volunteers in current maintainers and participants can help on maintain the project. 
2. Pedro and Ludovic can leave some guidance on what need to do, and how we can proceed. 

If no one volunteer to maintian, then we consider to lower down the meeting frequency.

**Comment by PedroDiez** [comment]
Already managed
