### ISSUE TITLE
Improvement suggestions for merged API

### ISSUE THREAD

**Issue by eragaji** [camaraproject/CarrierBillingCheckOut#91]
This issue is for the GET /payments API of the new merged proposal.
For the GET /payments API proposed, there are no filter parameters which are proposed.
Because of this, this API will return all payments there in the system and not just the payments belonging to a particular merchant.
We need to have merchant identifier as mandatory parameter to limit the payment information returned back to the merchant. 
Please do note that we might have an aggregator in between the merchant application and the Carrier Billing service and in that scenario token might not be helpful to identify the merchant.

Also ideally we should support additional filter parameters like date range for which payment records are needed or payments of specific status. Merchants usually are interested in getting payments for a specific date range or status.

**Comment by PedroDiez** [comment]
Ericsson view:
 - mandatory: merchantId (merchantInformation)
 - optional: date range, status
 
Orange view:
- merchantInfo, date range, status all optional.
- API logic must ensure payments retrieved are the ones performed via the same "client_id" understood as the API client

Telefonica view:
- Indicates it shares view about list payments for a given "oAuth client", and optionality about merchantInfo, date range status.
- Elaborate proposal and trigger PR

**Comment by PedroDiez** [comment]
Related PR: https://github.com/camaraproject/CarrierBillingCheckOut/pull/96

**Comment by PedroDiez** [comment]
Closed as PR Merged
