### ISSUE TITLE
Documentation Update in Carrier Billing WG

### ISSUE THREAD

**Issue by PedroDiez** [camaraproject/CarrierBillingCheckOut#93]
**Problem description**
Once a common proposal has been agreed. There is some documentation that need to be updated/removed

**Expected action**
Identify points of documentation update. Indicate here an make subsequent PRs to ammend it.

- [x] Working Group Name. Maybe rename to Carrier Billing. Need to check with Markus in advance. This is 'cosmetic' update, think this is not a matter in case doing that change implies lot of procedures and Markus does not believe necessary
- [x] README.md at 'root' directory. "Notice for the reader": delete action. "Scope" section: Update. Check link for the meetings is current one.
- [x] /code/API_definitions/ folder. Keep only current carrier_billing.yaml. Rest of files move them to /documentation/SupportingDocuments/
- [x] /documentation/API_documentation/ folder. Need to check jointly with Ludovic on his back (@bigludo7). Some files probably to be deleted, other ones to be reviewed and renamed.

**Comment by PedroDiez** [comment]
`/code/API_definitions/ folder. Keep only current carrier_billing.yaml. Rest of files move them to /documentation/SupportingDocuments/`

Related PR: https://github.com/camaraproject/CarrierBillingCheckOut/pull/94

**Comment by PedroDiez** [comment]
`one of the GitHub admins only can do this change. It’s possible but means effort, it’s not simple.
We have to change the readme.md, the website, the CAMARA presentation, all the links pointing to that repo.
`

Have checked with Markus and it implies huge extra effort. Let's keep as-is. 01/AGO DONE

**Comment by PedroDiez** [comment]
>   README.md at 'root' directory. "Notice for the reader": delete action. "Scope" section: Update. Check link for the meetings is current one.

Related PR: https://github.com/camaraproject/CarrierBillingCheckOut/pull/95. MERGED 17/AGO. DONE

**Comment by PedroDiez** [comment]
` /documentation/API_documentation/ folder. Need to check jointly with Ludovic on his back (@bigludo7). Some files probably to be deleted, other ones to be reviewed and renamed.`

Part 1: https://github.com/camaraproject/CarrierBillingCheckOut/pull/99

**Comment by bigludo7** [comment]
Done some part here #100  ;)

**Comment by PedroDiez** [comment]
Closed as all points driven
